// src/features/extreme-users/types.ts

export type UserClassification = "super-experto" | "inexperto" | "mainstream";

export interface ExtremeUser {
  id: string; // generated by lib/list.ts, never set manually
  classification: UserClassification;
  alias: string;
  usageContext: string;
  usageFrequency: string;
  skillLevel: number; // 1-10
  observedTasks: string[];
  workarounds: string[];
  amplifiedFrictions: string[];
  extremeNeed: string;
  generalizationHypothesis: string;
  evidence: string[];
}

export const CLASSIFICATION_LABELS: Record<UserClassification, string> = {
  "super-experto": "Súper-experto",
  "inexperto": "Inexperto",
  "mainstream": "Mainstream",
};
